export const sampleCategories = [
  {
    id: "cat-1",
    name: "Menswear",
    slug: "menswear",
    description: "Premium menswear collection featuring tailored essentials and modern streetwear",
    image: "https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&q=80",
    featured: true,
  },
  {
    id: "cat-2",
    name: "Womenswear",
    slug: "womenswear",
    description: "Curated womenswear blending elegance with contemporary edge",
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=80",
    featured: true,
  },
  {
    id: "cat-3",
    name: "Accessories",
    slug: "accessories",
    description: "Statement accessories to complete every look",
    image: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&q=80",
    featured: true,
  },
  {
    id: "cat-4",
    name: "Footwear",
    slug: "footwear",
    description: "Luxury footwear crafted for comfort and style",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80",
    featured: true,
  },
  {
    id: "cat-5",
    name: "Outerwear",
    slug: "outerwear",
    description: "Premium outerwear for every season",
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&q=80",
    featured: false,
  },
  {
    id: "cat-6",
    name: "Streetwear",
    slug: "streetwear",
    description: "Bold streetwear for the culture",
    image: "https://images.unsplash.com/photo-1523398002811-999ca8dec234?w=800&q=80",
    featured: false,
  },
];

export const sampleProducts = [
  {
    id: "prod-1",
    name: "Noir Tailored Blazer",
    slug: "noir-tailored-blazer",
    description: "A sharply cut blazer in midnight black Italian wool. Notch lapels, double-button closure, and a slim silhouette that transitions effortlessly from the boardroom to an evening out. Fully lined with our signature gold interior.",
    price: 485,
    comparePrice: 650,
    currency: "USD",
    sku: "ARL-BLZ-001",
    categoryId: "cat-1",
    featured: true,
    isNew: false,
    isBestseller: true,
    published: true,
    images: [
      { id: "img-1a", url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80", alt: "Noir Tailored Blazer front", position: 0 },
      { id: "img-1b", url: "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=800&q=80", alt: "Noir Tailored Blazer detail", position: 1 },
    ],
    variants: [
      { id: "var-1a", size: "S", color: "Black", colorHex: "#000000", stock: 12, sku: "ARL-BLZ-001-S" },
      { id: "var-1b", size: "M", color: "Black", colorHex: "#000000", stock: 18, sku: "ARL-BLZ-001-M" },
      { id: "var-1c", size: "L", color: "Black", colorHex: "#000000", stock: 15, sku: "ARL-BLZ-001-L" },
      { id: "var-1d", size: "XL", color: "Black", colorHex: "#000000", stock: 8, sku: "ARL-BLZ-001-XL" },
    ],
    reviews: [
      { id: "rev-1a", rating: 5, title: "Exceptional quality", comment: "The fit is perfect and the fabric feels luxurious. Worth every penny.", verified: true, user: { name: "James K." } },
      { id: "rev-1b", rating: 4, title: "Great blazer", comment: "Sleek design. Slightly long in the sleeves for me but tailoring fixed that.", verified: true, user: { name: "Michael T." } },
    ],
  },
  {
    id: "prod-2",
    name: "Ivory Silk Wrap Dress",
    slug: "ivory-silk-wrap-dress",
    description: "Effortlessly draped in pure mulberry silk, this wrap dress falls just below the knee with a flattering V-neckline and adjustable tie waist. The ivory tone works year-round, dressed up with heels or down with flats.",
    price: 395,
    comparePrice: null,
    currency: "USD",
    sku: "ARL-DRS-002",
    categoryId: "cat-2",
    featured: true,
    isNew: true,
    isBestseller: false,
    published: true,
    images: [
      { id: "img-2a", url: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80", alt: "Ivory Silk Wrap Dress", position: 0 },
      { id: "img-2b", url: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&q=80", alt: "Ivory Silk Wrap Dress styled", position: 1 },
    ],
    variants: [
      { id: "var-2a", size: "XS", color: "Ivory", colorHex: "#FFFFF0", stock: 6, sku: "ARL-DRS-002-XS" },
      { id: "var-2b", size: "S", color: "Ivory", colorHex: "#FFFFF0", stock: 14, sku: "ARL-DRS-002-S" },
      { id: "var-2c", size: "M", color: "Ivory", colorHex: "#FFFFF0", stock: 10, sku: "ARL-DRS-002-M" },
      { id: "var-2d", size: "L", color: "Ivory", colorHex: "#FFFFF0", stock: 7, sku: "ARL-DRS-002-L" },
    ],
    reviews: [
      { id: "rev-2a", rating: 5, title: "Absolutely stunning", comment: "This dress is gorgeous. The silk quality is remarkable and the fit is so flattering.", verified: true, user: { name: "Sarah L." } },
    ],
  },
  {
    id: "prod-3",
    name: "Heritage Leather Tote",
    slug: "heritage-leather-tote",
    description: "Hand-stitched from full-grain vegetable-tanned leather, this structured tote ages beautifully with use. Features brass hardware, an interior zip pocket, and dual carrying handles with a removable shoulder strap.",
    price: 320,
    comparePrice: 420,
    currency: "USD",
    sku: "ARL-BAG-003",
    categoryId: "cat-3",
    featured: true,
    isNew: false,
    isBestseller: true,
    published: true,
    images: [
      { id: "img-3a", url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80", alt: "Heritage Leather Tote", position: 0 },
      { id: "img-3b", url: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80", alt: "Heritage Leather Tote detail", position: 1 },
    ],
    variants: [
      { id: "var-3a", color: "Cognac", colorHex: "#9A463D", stock: 22, sku: "ARL-BAG-003-COG" },
      { id: "var-3b", color: "Black", colorHex: "#000000", stock: 18, sku: "ARL-BAG-003-BLK" },
      { id: "var-3c", color: "Tan", colorHex: "#D2B48C", stock: 9, sku: "ARL-BAG-003-TAN" },
    ],
    reviews: [
      { id: "rev-3a", rating: 5, title: "Best bag I own", comment: "Incredible quality leather. Gets better with age.", verified: true, user: { name: "Amara N." } },
      { id: "rev-3b", rating: 5, title: "A forever piece", comment: "Exactly what I was looking for. Spacious and sturdy.", verified: true, user: { name: "Olivia R." } },
    ],
  },
  {
    id: "prod-4",
    name: "Atlas Runner Sneakers",
    slug: "atlas-runner-sneakers",
    description: "Engineered for all-day comfort with a chunky sole, breathable mesh upper, and premium suede overlays. The Atlas Runner combines street-ready aesthetics with performance cushioning. Runs true to size.",
    price: 225,
    comparePrice: null,
    currency: "USD",
    sku: "ARL-SNK-004",
    categoryId: "cat-4",
    featured: false,
    isNew: true,
    isBestseller: true,
    published: true,
    images: [
      { id: "img-4a", url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80", alt: "Atlas Runner Sneakers", position: 0 },
      { id: "img-4b", url: "https://images.unsplash.com/photo-1556048219-bb6978360b84?w=800&q=80", alt: "Atlas Runner Sneakers side", position: 1 },
    ],
    variants: [
      { id: "var-4a", size: "8", color: "Off-White", colorHex: "#FAF0E6", stock: 20, sku: "ARL-SNK-004-8" },
      { id: "var-4b", size: "9", color: "Off-White", colorHex: "#FAF0E6", stock: 25, sku: "ARL-SNK-004-9" },
      { id: "var-4c", size: "10", color: "Off-White", colorHex: "#FAF0E6", stock: 22, sku: "ARL-SNK-004-10" },
      { id: "var-4d", size: "11", color: "Off-White", colorHex: "#FAF0E6", stock: 15, sku: "ARL-SNK-004-11" },
      { id: "var-4e", size: "12", color: "Off-White", colorHex: "#FAF0E6", stock: 10, sku: "ARL-SNK-004-12" },
    ],
    reviews: [
      { id: "rev-4a", rating: 4, title: "Comfortable and stylish", comment: "Wore them all day on a trip — no complaints.", verified: true, user: { name: "David P." } },
    ],
  },
  {
    id: "prod-5",
    name: "Obsidian Overcoat",
    slug: "obsidian-overcoat",
    description: "A statement overcoat in heavyweight wool-cashmere blend. Double-breasted with a peak lapel and knee-length cut. Fully lined in satin with interior pockets. The kind of coat that makes people look twice.",
    price: 780,
    comparePrice: 950,
    currency: "USD",
    sku: "ARL-COT-005",
    categoryId: "cat-5",
    featured: true,
    isNew: false,
    isBestseller: false,
    published: true,
    images: [
      { id: "img-5a", url: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&q=80", alt: "Obsidian Overcoat", position: 0 },
      { id: "img-5b", url: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&q=80", alt: "Obsidian Overcoat back", position: 1 },
    ],
    variants: [
      { id: "var-5a", size: "S", color: "Charcoal", colorHex: "#36454F", stock: 5, sku: "ARL-COT-005-S" },
      { id: "var-5b", size: "M", color: "Charcoal", colorHex: "#36454F", stock: 8, sku: "ARL-COT-005-M" },
      { id: "var-5c", size: "L", color: "Charcoal", colorHex: "#36454F", stock: 6, sku: "ARL-COT-005-L" },
      { id: "var-5d", size: "XL", color: "Charcoal", colorHex: "#36454F", stock: 3, sku: "ARL-COT-005-XL" },
    ],
    reviews: [],
  },
  {
    id: "prod-6",
    name: "Muse Cropped Hoodie",
    slug: "muse-cropped-hoodie",
    description: "Heavyweight 400gsm French terry hoodie with a relaxed, cropped fit. Features a kangaroo pocket, ribbed cuffs, and our embossed logo at the chest. Preshrunk and garment-dyed for a lived-in feel from day one.",
    price: 165,
    comparePrice: null,
    currency: "USD",
    sku: "ARL-HDY-006",
    categoryId: "cat-6",
    featured: false,
    isNew: true,
    isBestseller: false,
    published: true,
    images: [
      { id: "img-6a", url: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80", alt: "Muse Cropped Hoodie", position: 0 },
      { id: "img-6b", url: "https://images.unsplash.com/photo-1578768079470-0a4536cc7f33?w=800&q=80", alt: "Muse Cropped Hoodie back", position: 1 },
    ],
    variants: [
      { id: "var-6a", size: "S", color: "Washed Black", colorHex: "#2C2C2C", stock: 30, sku: "ARL-HDY-006-S-BLK" },
      { id: "var-6b", size: "M", color: "Washed Black", colorHex: "#2C2C2C", stock: 35, sku: "ARL-HDY-006-M-BLK" },
      { id: "var-6c", size: "L", color: "Washed Black", colorHex: "#2C2C2C", stock: 28, sku: "ARL-HDY-006-L-BLK" },
      { id: "var-6d", size: "S", color: "Sand", colorHex: "#C2B280", stock: 20, sku: "ARL-HDY-006-S-SND" },
      { id: "var-6e", size: "M", color: "Sand", colorHex: "#C2B280", stock: 22, sku: "ARL-HDY-006-M-SND" },
      { id: "var-6f", size: "L", color: "Sand", colorHex: "#C2B280", stock: 18, sku: "ARL-HDY-006-L-SND" },
    ],
    reviews: [
      { id: "rev-6a", rating: 5, title: "Perfect weight", comment: "Thick but not too heavy. The washed texture is amazing.", verified: true, user: { name: "Kofi A." } },
    ],
  },
  {
    id: "prod-7",
    name: "Crescent Knit Polo",
    slug: "crescent-knit-polo",
    description: "A refined take on the classic polo, knitted from Egyptian cotton with a textured weave. Ribbed collar and cuffs, mother-of-pearl buttons, and a relaxed fit that sits perfectly untucked.",
    price: 145,
    comparePrice: 185,
    currency: "USD",
    sku: "ARL-POL-007",
    categoryId: "cat-1",
    featured: false,
    isNew: false,
    isBestseller: true,
    published: true,
    images: [
      { id: "img-7a", url: "https://images.unsplash.com/photo-1625910513413-5fc421e0a7dc?w=800&q=80", alt: "Crescent Knit Polo", position: 0 },
      { id: "img-7b", url: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800&q=80", alt: "Crescent Knit Polo styled", position: 1 },
    ],
    variants: [
      { id: "var-7a", size: "S", color: "Navy", colorHex: "#1B1F3B", stock: 15, sku: "ARL-POL-007-S-NVY" },
      { id: "var-7b", size: "M", color: "Navy", colorHex: "#1B1F3B", stock: 20, sku: "ARL-POL-007-M-NVY" },
      { id: "var-7c", size: "L", color: "Navy", colorHex: "#1B1F3B", stock: 18, sku: "ARL-POL-007-L-NVY" },
      { id: "var-7d", size: "S", color: "Cream", colorHex: "#FFFDD0", stock: 12, sku: "ARL-POL-007-S-CRM" },
      { id: "var-7e", size: "M", color: "Cream", colorHex: "#FFFDD0", stock: 16, sku: "ARL-POL-007-M-CRM" },
      { id: "var-7f", size: "L", color: "Cream", colorHex: "#FFFDD0", stock: 14, sku: "ARL-POL-007-L-CRM" },
    ],
    reviews: [
      { id: "rev-7a", rating: 5, title: "Elevated casual", comment: "Better than any polo I've owned. The knit fabric sets it apart.", verified: true, user: { name: "Ethan W." } },
      { id: "rev-7b", rating: 4, title: "Nice piece", comment: "Great quality. Runs slightly large — consider sizing down.", verified: true, user: { name: "Ryan M." } },
    ],
  },
  {
    id: "prod-8",
    name: "Velvet Evening Clutch",
    slug: "velvet-evening-clutch",
    description: "A sculptural clutch in crushed velvet with a magnetic clasp and gold-tone chain strap. Interior lined in suede with a card slot. Small enough to carry essentials, striking enough to start conversations.",
    price: 195,
    comparePrice: null,
    currency: "USD",
    sku: "ARL-CLT-008",
    categoryId: "cat-3",
    featured: false,
    isNew: true,
    isBestseller: false,
    published: true,
    images: [
      { id: "img-8a", url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80", alt: "Velvet Evening Clutch", position: 0 },
      { id: "img-8b", url: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&q=80", alt: "Velvet Evening Clutch open", position: 1 },
    ],
    variants: [
      { id: "var-8a", color: "Burgundy", colorHex: "#800020", stock: 15, sku: "ARL-CLT-008-BRG" },
      { id: "var-8b", color: "Emerald", colorHex: "#50C878", stock: 12, sku: "ARL-CLT-008-EMR" },
      { id: "var-8c", color: "Midnight", colorHex: "#191970", stock: 10, sku: "ARL-CLT-008-MID" },
    ],
    reviews: [],
  },
  {
    id: "prod-9",
    name: "Monolith Chelsea Boots",
    slug: "monolith-chelsea-boots",
    description: "Built on a commando sole with a chunky profile, these Chelsea boots balance rugged with refined. Full-grain leather upper, elastic side panels, and a pull tab at the heel. Goodyear welted for longevity.",
    price: 345,
    comparePrice: 425,
    currency: "USD",
    sku: "ARL-BTS-009",
    categoryId: "cat-4",
    featured: true,
    isNew: false,
    isBestseller: true,
    published: true,
    images: [
      { id: "img-9a", url: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=800&q=80", alt: "Monolith Chelsea Boots", position: 0 },
      { id: "img-9b", url: "https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=800&q=80", alt: "Monolith Chelsea Boots pair", position: 1 },
    ],
    variants: [
      { id: "var-9a", size: "8", color: "Black", colorHex: "#000000", stock: 10, sku: "ARL-BTS-009-8" },
      { id: "var-9b", size: "9", color: "Black", colorHex: "#000000", stock: 14, sku: "ARL-BTS-009-9" },
      { id: "var-9c", size: "10", color: "Black", colorHex: "#000000", stock: 12, sku: "ARL-BTS-009-10" },
      { id: "var-9d", size: "11", color: "Black", colorHex: "#000000", stock: 8, sku: "ARL-BTS-009-11" },
    ],
    reviews: [
      { id: "rev-9a", rating: 5, title: "Tank-like boots", comment: "Heavy-duty but incredibly comfortable once broken in. The sole is incredible.", verified: true, user: { name: "Nathan G." } },
    ],
  },
  {
    id: "prod-10",
    name: "Sovereign Linen Shirt",
    slug: "sovereign-linen-shirt",
    description: "Cut from premium Belgian linen with a slightly oversized fit. Camp collar, coconut shell buttons, and a single chest pocket. Pre-washed for softness — no stiff break-in period. The definitive summer shirt.",
    price: 175,
    comparePrice: null,
    currency: "USD",
    sku: "ARL-SHT-010",
    categoryId: "cat-1",
    featured: false,
    isNew: true,
    isBestseller: false,
    published: true,
    images: [
      { id: "img-10a", url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80", alt: "Sovereign Linen Shirt", position: 0 },
      { id: "img-10b", url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80", alt: "Sovereign Linen Shirt back", position: 1 },
    ],
    variants: [
      { id: "var-10a", size: "S", color: "White", colorHex: "#FFFFFF", stock: 20, sku: "ARL-SHT-010-S-WHT" },
      { id: "var-10b", size: "M", color: "White", colorHex: "#FFFFFF", stock: 25, sku: "ARL-SHT-010-M-WHT" },
      { id: "var-10c", size: "L", color: "White", colorHex: "#FFFFFF", stock: 22, sku: "ARL-SHT-010-L-WHT" },
      { id: "var-10d", size: "S", color: "Sage", colorHex: "#BCB88A", stock: 15, sku: "ARL-SHT-010-S-SGE" },
      { id: "var-10e", size: "M", color: "Sage", colorHex: "#BCB88A", stock: 18, sku: "ARL-SHT-010-M-SGE" },
      { id: "var-10f", size: "L", color: "Sage", colorHex: "#BCB88A", stock: 14, sku: "ARL-SHT-010-L-SGE" },
    ],
    reviews: [
      { id: "rev-10a", rating: 5, title: "Summer essential", comment: "Breathes like a dream. Best linen shirt in this price range.", verified: true, user: { name: "Tunde B." } },
    ],
  },
  {
    id: "prod-11",
    name: "Aura Cashmere Sweater",
    slug: "aura-cashmere-sweater",
    description: "Pure Grade-A Mongolian cashmere knitted into a crew-neck sweater with a relaxed drape. Incredibly soft with a satisfying weight. Features ribbed hem and cuffs with a touch of stretch for movement.",
    price: 420,
    comparePrice: 520,
    currency: "USD",
    sku: "ARL-SWT-011",
    categoryId: "cat-2",
    featured: true,
    isNew: false,
    isBestseller: true,
    published: true,
    images: [
      { id: "img-11a", url: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80", alt: "Aura Cashmere Sweater", position: 0 },
      { id: "img-11b", url: "https://images.unsplash.com/photo-1434389677669-e08b4cda3a22?w=800&q=80", alt: "Aura Cashmere Sweater detail", position: 1 },
    ],
    variants: [
      { id: "var-11a", size: "XS", color: "Oatmeal", colorHex: "#C8AD7F", stock: 8, sku: "ARL-SWT-011-XS" },
      { id: "var-11b", size: "S", color: "Oatmeal", colorHex: "#C8AD7F", stock: 12, sku: "ARL-SWT-011-S" },
      { id: "var-11c", size: "M", color: "Oatmeal", colorHex: "#C8AD7F", stock: 15, sku: "ARL-SWT-011-M" },
      { id: "var-11d", size: "L", color: "Oatmeal", colorHex: "#C8AD7F", stock: 10, sku: "ARL-SWT-011-L" },
    ],
    reviews: [
      { id: "rev-11a", rating: 5, title: "Unreal softness", comment: "You can feel the quality the second you put it on. Will buy more colors.", verified: true, user: { name: "Priya S." } },
    ],
  },
  {
    id: "prod-12",
    name: "Drift Cargo Trousers",
    slug: "drift-cargo-trousers",
    description: "Relaxed-fit cargo trousers in a washed cotton twill with an elastic waistband and drawstring. Six-pocket design with flap closures and tapered leg. Garment-dyed for a vintage wash effect.",
    price: 185,
    comparePrice: null,
    currency: "USD",
    sku: "ARL-TRS-012",
    categoryId: "cat-6",
    featured: false,
    isNew: true,
    isBestseller: false,
    published: true,
    images: [
      { id: "img-12a", url: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80", alt: "Drift Cargo Trousers", position: 0 },
      { id: "img-12b", url: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80", alt: "Drift Cargo Trousers styled", position: 1 },
    ],
    variants: [
      { id: "var-12a", size: "S", color: "Olive", colorHex: "#808000", stock: 18, sku: "ARL-TRS-012-S-OLV" },
      { id: "var-12b", size: "M", color: "Olive", colorHex: "#808000", stock: 24, sku: "ARL-TRS-012-M-OLV" },
      { id: "var-12c", size: "L", color: "Olive", colorHex: "#808000", stock: 20, sku: "ARL-TRS-012-L-OLV" },
      { id: "var-12d", size: "XL", color: "Olive", colorHex: "#808000", stock: 12, sku: "ARL-TRS-012-XL-OLV" },
    ],
    reviews: [],
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Adaeze Okonkwo",
    location: "Lagos, Nigeria",
    rating: 5,
    comment: "Arlotech has completely changed how I shop. The quality is unmatched and every piece feels like it was designed specifically for me. I've placed six orders and every single one exceeded expectations.",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&q=80",
  },
  {
    id: 2,
    name: "Tunde Adeyemi",
    location: "Abuja, Nigeria",
    rating: 5,
    comment: "Finally a Nigerian brand that competes with the best in the world. The blazer fits perfectly, the fabric is premium, and the packaging is world-class. Very proud to support local.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&q=80",
  },
  {
    id: 3,
    name: "Marcus Chen",
    location: "London, UK",
    rating: 5,
    comment: "Found Arlotech through a friend in Lagos. The tailored blazer is hands down the best piece in my wardrobe. Shipping to London was faster than expected — arrived in 5 days.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
  },
  {
    id: 4,
    name: "Chioma Eze",
    location: "Port Harcourt, Nigeria",
    rating: 5,
    comment: "I am very particular about quality and Arlotech delivers every single time. The cashmere sweater is buttery soft and the leather tote has become my everyday bag. Absolutely love this brand.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
  },
];
